# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f47c6f59416ef11d337c0444beac3faf5ecb6b153958146b7f5adaf4091d61feaf745e6ccadd8fed53a6489152ea4126a9b237071ba9d51c0ec169bfcc4aa5f

test:
  secret_key_base: 4746ed7feddb62e2cb85b6474763d419876f3b1c051c8a9356816701a200490b65900f2c8f344a9eb325e38ecb18aa97b700e91ab55f79ce87368aeacee0c7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
